# Generated by Django 6.0.5 on 2026-05-27 03:42

import core.models
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Account',
            fields=[
                ('id_account', models.AutoField(primary_key=True, serialize=False)),
                ('account_name', models.CharField(max_length=100)),
                ('account_type', models.CharField(choices=[('ACTIVO', 'Activo'), ('PASIVO', 'Pasivo'), ('CAPITAL', 'Capital'), ('INGRESO', 'Ingreso'), ('GASTO', 'Gasto')], max_length=10)),
                ('currency', models.CharField(max_length=3)),
                ('creation_date', models.DateTimeField(auto_now_add=True)),
                ('deleted_at', models.DateTimeField(default=core.models.future_date)),
            ],
            options={
                'db_table': 'ACCOUNT',
            },
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id_category', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50)),
                ('type', models.CharField(choices=[('EXPENSE', 'Expense'), ('INCOME', 'Income')], max_length=10)),
                ('description', models.CharField(blank=True, max_length=255, null=True)),
                ('color', models.CharField(blank=True, max_length=7, null=True)),
                ('creation_date', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'CATEGORY',
            },
        ),
        migrations.CreateModel(
            name='ExchangeRate',
            fields=[
                ('id_exchange_rate', models.AutoField(primary_key=True, serialize=False)),
                ('from_currency', models.CharField(max_length=3)),
                ('to_currency', models.CharField(max_length=3)),
                ('rate', models.DecimalField(decimal_places=4, max_digits=10)),
                ('rate_date', models.DateTimeField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'EXCHANGE_RATE',
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id_user', models.AutoField(primary_key=True, serialize=False)),
                ('first_name', models.CharField(max_length=100)),
                ('last_name_1', models.CharField(max_length=100)),
                ('last_name_2', models.CharField(blank=True, max_length=100, null=True)),
                ('email', models.EmailField(max_length=100, unique=True)),
                ('password_hash', models.CharField(max_length=255)),
                ('password_hash_2', models.CharField(blank=True, max_length=255, null=True)),
                ('registration_date', models.DateTimeField(auto_now_add=True)),
                ('cancellation_date', models.DateTimeField(default=core.models.future_date)),
            ],
            options={
                'db_table': 'USER',
            },
        ),
        migrations.CreateModel(
            name='AccountLimit',
            fields=[
                ('id_limit', models.AutoField(primary_key=True, serialize=False)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('max_amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('id_account', models.ForeignKey(db_column='id_account', on_delete=django.db.models.deletion.CASCADE, to='core.account')),
            ],
            options={
                'db_table': 'ACCOUNT_LIMIT',
            },
        ),
        migrations.AddField(
            model_name='account',
            name='id_main_category',
            field=models.ForeignKey(blank=True, db_column='id_main_category', null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.category'),
        ),
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id_service', models.AutoField(primary_key=True, serialize=False)),
                ('service_name', models.CharField(max_length=100)),
                ('provider_name', models.CharField(blank=True, max_length=100, null=True)),
                ('reference_number', models.CharField(blank=True, max_length=100, null=True)),
                ('due_day', models.IntegerField()),
                ('payment_interval_months', models.IntegerField(default=1)),
                ('typical_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('currency', models.CharField(max_length=3)),
                ('cancellation_date', models.DateTimeField(default=core.models.future_date)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('id_user', models.ForeignKey(db_column='id_user', on_delete=django.db.models.deletion.CASCADE, to='core.user')),
            ],
            options={
                'db_table': 'SERVICE',
            },
        ),
        migrations.AddField(
            model_name='category',
            name='id_user',
            field=models.ForeignKey(db_column='id_user', on_delete=django.db.models.deletion.CASCADE, to='core.user'),
        ),
        migrations.AddField(
            model_name='account',
            name='id_user',
            field=models.ForeignKey(db_column='id_user', on_delete=django.db.models.deletion.CASCADE, to='core.user'),
        ),
        migrations.CreateModel(
            name='Movement',
            fields=[
                ('id_movement', models.AutoField(primary_key=True, serialize=False)),
                ('transfer_group_id', models.IntegerField(blank=True, null=True)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('original_currency', models.CharField(max_length=3)),
                ('description', models.CharField(blank=True, max_length=255, null=True)),
                ('movement_date', models.DateField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('id_account', models.ForeignKey(db_column='id_account', on_delete=django.db.models.deletion.CASCADE, related_name='movements', to='core.account')),
                ('id_category', models.ForeignKey(db_column='id_category', on_delete=django.db.models.deletion.CASCADE, to='core.category')),
                ('id_destination_account', models.ForeignKey(blank=True, db_column='id_destination_account', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='destination_movements', to='core.account')),
                ('id_exchange_rate', models.ForeignKey(blank=True, db_column='id_exchange_rate', null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.exchangerate')),
                ('id_service', models.ForeignKey(blank=True, db_column='id_service', null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.service')),
            ],
            options={
                'db_table': 'MOVEMENT',
                'indexes': [models.Index(fields=['id_account'], name='MOVEMENT_id_acco_3e930f_idx'), models.Index(fields=['id_category'], name='MOVEMENT_id_cate_faa409_idx'), models.Index(fields=['movement_date'], name='MOVEMENT_movemen_319bab_idx'), models.Index(fields=['transfer_group_id'], name='MOVEMENT_transfe_ed535d_idx')],
            },
        ),
        migrations.AddConstraint(
            model_name='category',
            constraint=models.UniqueConstraint(fields=('id_user', 'name', 'type'), name='uq_category_user_name_type'),
        ),
    ]
