# Generated by Django 6.0.4 on 2026-04-28 22:25

import core.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='account',
            options={},
        ),
        migrations.AlterModelOptions(
            name='accountlimit',
            options={},
        ),
        migrations.AlterModelOptions(
            name='category',
            options={},
        ),
        migrations.AlterModelOptions(
            name='exchangerate',
            options={},
        ),
        migrations.AlterModelOptions(
            name='movement',
            options={},
        ),
        migrations.AlterModelOptions(
            name='service',
            options={},
        ),
        migrations.AlterModelOptions(
            name='user',
            options={},
        ),
        migrations.RemoveIndex(
            model_name='exchangerate',
            name='EXCHANGE_RA_from_cu_87d86e_idx',
        ),
        migrations.AlterField(
            model_name='account',
            name='deleted_at',
            field=models.DateTimeField(default=core.models.future_date),
        ),
        migrations.AlterField(
            model_name='accountlimit',
            name='max_amount',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
        migrations.AlterField(
            model_name='exchangerate',
            name='rate',
            field=models.DecimalField(decimal_places=4, max_digits=10),
        ),
        migrations.AlterField(
            model_name='service',
            name='cancellation_date',
            field=models.DateTimeField(default=core.models.future_date),
        ),
        migrations.AlterField(
            model_name='service',
            name='due_day',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='user',
            name='cancellation_date',
            field=models.DateTimeField(default=core.models.future_date),
        ),
    ]
